### ISSUE TITLE
docker logs and /var/log/startup.log

### ISSUE THREAD

**Issue by JuustoMestari** [nimmis/docker-alpine#2]
Hello,

I have created a supervisor conf file that executes a python script. I have added _stdout_logfile=/var/log/startup.log_ in that configuration. The python script runs fine and logs correctly in /var/log/startup.log but I cannot see the log when I run docker logs [container_name]. 
Do you know what might be the issue?

Thanks !

**Comment by nimmis** [comment]
Docker logs only show text that you are printing to the console, so instead of sending it to a file echo it to the standard out
